#!/usr/bin/env python3
"""Self-host Manrope & Inter (latin subset, variable-weight files as served by Google Fonts)."""
import re, os, urllib.request

BASE = os.path.join(os.path.dirname(__file__), "..")
FONTDIR = os.path.join(BASE, "public/fonts")
os.makedirs(FONTDIR, exist_ok=True)
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"}

def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    return urllib.request.urlopen(req, timeout=30).read()

css_out = ["/* Self-hosted Manrope & Inter — from Google Fonts (SIL OFL). Generated by scripts/fetch-fonts.py */"]
for fam, q in [("Manrope", "Manrope:wght@600..800"), ("Inter", "Inter:wght@400..700")]:
    css = fetch(f"https://fonts.googleapis.com/css2?family={q}&display=swap").decode()
    for subset, face in re.findall(r"/\* (\w[\w-]*) \*/\s*(@font-face\s*\{[^}]+\})", css):
        if subset != "latin":
            continue
        src = re.search(r"url\((https://[^)]+\.woff2)\)", face)
        if not src:
            continue
        fname = f"{fam.lower()}-latin.woff2"
        if not os.path.exists(os.path.join(FONTDIR, fname)):
            open(os.path.join(FONTDIR, fname), "wb").write(fetch(src.group(1)))
        weight = re.search(r"font-weight:\s*([\d ]+);", face)
        weight = weight.group(1).strip() if weight else "400 700"
        css_out.append(
            f"@font-face{{font-family:'{fam}';font-style:normal;font-weight:{weight};font-display:swap;"
            f"src:url('/fonts/{fname}') format('woff2');}}"
        )

open(os.path.join(BASE, "src/styles/fonts.css"), "w").write("\n".join(css_out) + "\n")
print("fonts:", os.listdir(FONTDIR))
