const { chromium } = require("playwright");
(async () => {
  const b = await chromium.launch({ args: ["--no-sandbox"] });
  const pg = await b.newPage({ viewport: { width: 1440, height: 900 } });
  await pg.goto("http://localhost:5173/", { waitUntil: "networkidle" });
  await pg.screenshot({ path: "qa/home-hero.png" });
  await pg.evaluate(() => document.querySelector("#trust")?.scrollIntoView());
  await pg.waitForTimeout(700);
  await pg.screenshot({ path: "qa/home-trust.png" });
  await pg.evaluate(() => Array.from(document.querySelectorAll("h2")).find(h => /global opportunities/i.test(h.textContent))?.scrollIntoView({block:"center"}));
  await pg.waitForTimeout(900);
  await pg.screenshot({ path: "qa/home-map.png" });
  await pg.goto("http://localhost:5173/employers", { waitUntil: "networkidle" });
  await pg.evaluate(() => window.scrollTo(0, 800));
  await pg.waitForTimeout(500);
  await pg.screenshot({ path: "qa/employer-form.png" });
  await pg.goto("http://localhost:5173/industries", { waitUntil: "networkidle" });
  await pg.evaluate(() => document.getElementById("marine")?.scrollIntoView());
  await pg.waitForTimeout(800);
  await pg.screenshot({ path: "qa/industry-marine.png" });
  await pg.goto("http://localhost:5173/job-categories", { waitUntil: "networkidle" });
  await pg.screenshot({ path: "qa/jobs.png" });
  const m = await b.newPage({ viewport: { width: 375, height: 812 } });
  await m.goto("http://localhost:5173/employers", { waitUntil: "networkidle" });
  await m.screenshot({ path: "qa/employer-m.png" });
  await m.goto("http://localhost:5173/", { waitUntil: "networkidle" });
  await m.evaluate(() => window.scrollTo(0, 700));
  await m.waitForTimeout(600);
  await m.screenshot({ path: "qa/home-m2.png" });
  await b.close();
  console.log("shots done");
})();
